name: Compilar Mission Control (Switch)

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: devkitpro/devkita64:latest

    steps:
    - name: Descargar el código fuente
      uses: actions/checkout@v4
      with:
        submodules: recursive 

    - name: Compilar el Sysmodule y Crear Release
      run: |
        make dist

    - name: Guardar el archivo compilado (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: MissionControl-Mod-Analogico
        path: "*.zip"
